# Spaceship Prompt Configuration

# Character
SPACESHIP_CHAR_SYMBOL="❯ "

# Time
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_12HR=true
SPACESHIP_TIME_SUFFIX=" | "

# Exit Code
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_SYMBOL="✘ "

# Command Execution Time
SPACESHIP_EXEC_TIME_ELAPSED=1

# User
SPACESHIP_USER_PREFIX="⚡ "

